### PR TITLE
fix: fix 500 error

### LINKED ISSUE #115: Bug: 500 Error on change organization city
When trying to change the city, the server returns a 500 error:
```
 [PUT /orgs/1] Response finished meta_code=500 response_body={
  "code": "500",
  "details": "ERROR:  syntax error at or near \"WHERE\"\nLINE 1: UPDATE organizations SET  WHERE id = $1 RETURNING id, name, ...\n                                  ^\n",
  "message": "Internal Server Error"
}
```

### PR DESCRIPTION
**Pull request by Granzh**

### CODE REVIEW

File: src/services/src/organization_service.cpp [hunk 1]
```diff
@@ -51,12 +51,16 @@ dto::OrganizationDTO OrganizationService::Update(
...
+    if (dto.city_id.has_value()) {
+        validated_city = city_service_.Get(*dto.city_id);
+    }
     models::Organization org = models::Organization::from_update_dto(org_id, dto);
     auto result = repository_.Update(org);
     if (!result) {
         throw OrganizationNotFoundException();
     }
-    auto city_dto = city_service_.Get(result->city_id);
+    auto city_dto = validated_city.has_value() ? std::move(*validated_city) : city_service_.Get(result->city_id);
```
Comment (Dark-Quant) [inline src/services/src/organization_service.cpp:63]: You should return nullopt if there isn't city with given id

**Review by Dark-Quant — CHANGES_REQUESTED** [review]

**Review by Dark-Quant — APPROVED** [review]
